name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # Kavita v$RESOLVED_VERSION

  $CHANGES
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'new'
      - 'added'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'fixed'
  - title: 'Changes'
    labels:
      - 'change'
      - 'changed'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'DevOps'
change-template: '- $BODY (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: feature'
  patch:
    labels:
      - 'type: bug'
      - 'type: maintenance'
      - 'type: docs'
      - 'type: dependencies'
      - 'type: security'
  default: patch
include-labels:
  - 'enhancement'
  - 'bug'
exclude-labels:
  - 'skip-changelog'
prerelease: true
