name: Nightly Workflow

on:
  push:
    branches: [ 'develop', '!release/**' ]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Not Contains Release: ${{ !contains(github.head_ref, 'release') }}"
          echo "Matches Develop: ${{ github.ref == 'refs/heads/develop' }}"
  build:
    name: Upload Kavita.Common for Version Bump
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/upload-artifact@v4
        with:
          name: csproj
          path: Kavita.Common/Kavita.Common.csproj

  version:
    name: Bump version
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.0.x

      - name: Bump versions
        uses: majora2007/dotnet-bump-version@v0.0.10
        with:
          version_files: Kavita.Common/Kavita.Common.csproj
          github_token: ${{ secrets.REPO_GHA_PAT }}
          version_mask: "0.0.0.1"

  develop:
    name: Build Nightly Docker
    needs: [ build, version ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    permissions:
      packages: write
      contents: read
    steps:
      - name: Find Current Pull Request
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: all
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse PR body
        id: parse-body
        run: |
          body="${{ steps.findPr.outputs.body }}"
          if [[ ${#body} -gt 1870 ]] ; then
            body=${body:0:1870}
            body="${body}...and much more.

            Read full changelog: https://github.com/Kareadita/Kavita/pull/${{ steps.findPr.outputs.pr }}"
          fi

          body=${body//\'/}
          body=${body//'%'/'%25'}
          body=${body//$'\n'/'%0A'}
          body=${body//$'\r'/'%0D'}
          body=${body//$'`'/'%60'}
          body=${body//$'>'/'%3E'}
          echo $body
          echo "BODY=$body" >> $GITHUB_OUTPUT

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: NodeJS to Compile WebUI
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          cd UI/Web || exit
          echo 'Installing web dependencies'
          npm install --legacy-peer-deps

          echo 'Building UI'
          npm run prod

          echo 'Copying back to Kavita wwwroot'
          rsync -a dist/ ../../API/wwwroot/

          cd ../ || exit

      - name: Get csproj Version
        uses: kzrnm/get-net-sdk-project-versions-action@v2
        id: get-version
        with:
          proj-path: Kavita.Common/Kavita.Common.csproj

      - name: Parse Version
        run: |
          version='${{steps.get-version.outputs.assembly-version}}'
          echo "VERSION=$version" >> $GITHUB_OUTPUT
        id: parse-version

      - name: Echo csproj version
        run: echo "${{steps.get-version.outputs.assembly-version}}"

      - name: Compile dotnet app
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.0.x

      - name: Install Swashbuckle CLI
        run: dotnet tool install -g --version 6.5.0 Swashbuckle.AspNetCore.Cli

      - run: ./monorepo-build.sh
