name: Release Drafter

on:
  push:
    branches:
      - feature/monorepo

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


